StringLiterals:
  EnforcedStyle: "double_quotes"

Style/FileName:
  Enabled: false

Documentation:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - rakelib/rubocop.rake

Metrics/LineLength:
  Exclude:
    - lib/more_view_hooks/default_additional_hooks.rb
